# Generated by Django 3.1 on 2020-08-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='competitor',
            constraint=models.CheckConstraint(check=models.Q(name__gt=''), name='arena_engine_competitor_not_blank'),
        ),
    ]
