# Generated by Django 3.1 on 2020-08-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arena_engine', '0002_auto_20200813_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='competitor',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MatchParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_number', models.PositiveSmallIntegerField()),
                ('starting_elo', models.SmallIntegerField(null=True)),
                ('resultant_elo', models.SmallIntegerField(null=True)),
                ('elo_change', models.SmallIntegerField(null=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_participations', to='arena_engine.competitor')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participants', to='arena_engine.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arena_engine.round'),
        ),
        migrations.AddConstraint(
            model_name='matchparticipation',
            constraint=models.UniqueConstraint(fields=('match', 'participant_number'), name='arena_engine_matchparticipation_unique_participant_number'),
        ),
        migrations.AlterUniqueTogether(
            name='matchparticipation',
            unique_together={('match', 'participant_number')},
        ),
    ]
